DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    token VARCHAR(50) NOT NULL,
    created DATE NOT NULL,
    modified DATE NOT NULL,
    last_login DATE NOT NULL,
    is_active INT(1) NOT NULL
);

DROP TABLE IF EXISTS PHONE;
CREATE TABLE PHONE (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    number VARCHAR(50) NOT NULL,
    city_code VARCHAR(50) NOT NULL,
    country_code VARCHAR(50) NOT NULL
    user_id INT NOT NULL,
    CONSTRAINT FK_USER_PHONE
    FOREIGN KEY user_id REFERENCES USER (id)
);